name: machine_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  better_player_plus: ^1.0.5

  bloc: ^8.1.4
  bot_toast: ^4.1.3
  cloud_firestore: ^4.15.8
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_storage: ^11.6.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_rating_bar: ^4.0.1
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  injectable: ^2.3.5
  pinput: ^4.0.0
  timer_count_down: ^2.2.2
  path_provider: ^2.1.3
  page_transition: ^2.1.0
  shared_preferences_riverpod: ^0.3.0
  rxdart: ^0.27.7
  pointycastle: ^3.9.0
  crypto: ^3.0.3
  http: ^1.2.1
  media_cache_manager: ^0.2.2
  encrypt: ^5.0.3
  permission_handler: ^11.3.1
  bloc_concurrency: ^0.2.5
  image_picker: ^1.1.0
  flutter_advanced_drawer: ^1.3.6
  no_screenshot: ^0.0.1+6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.4.7
  build_runner: ^2.4.8
  injectable_generator: ^2.4.2
  analyzer: ^6.4.1
  # android_permission:
  #   path: ./plugins/android_permission

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/lotties/
  

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
